[package]
name = "editr"
version = "0.1.0"
authors = ["Ben Lichtman"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
parking_lot = {version = "0.9", features = ["nightly"]}
